DROP TABLE data IF EXISTS;
DROP TABLE user IF EXISTS;
CREATE TABLE data(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), content TEXT, user_id LONG);
CREATE TABLE user(id LONG NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));